### PR TITLE
Use recommended versions (base/node/python) from upstream build instructions

### PR DESCRIPTION
**Pull request by ahinrichs**
See [XO installation docs](https://xen-orchestra.com/docs/installation.html#from-the-sources)

* update base image: node-18:bullseye
* python 2 -> python 3 in Dockerfile and run.sh
* added suggested packages from [#7095](https://github.com/vatesfr/xen-orchestra/issues/7095)

I just saw they suggest newer versions. So I tried and just made the minimal changes to make it build and run. Container logs show no difference to the docker hub image.

### CODE REVIEW

**Comment by thunderysteak** [comment]
When using the docker image during unrelated bug testing, Olivier Lambert has advised that Node 18 is an important per-requisite for running Xen Orchestra:
https://github.com/vatesfr/xen-orchestra/issues/7130#issuecomment-1781875628

**Comment by olivierlambert** [comment]
I mean, it's not even me, it's the official doc making it very clear :laughing: 

https://xen-orchestra.com/docs/installation.html#packages-and-pre-requisites

**Comment by ronivay** [comment]
Maintainer of this PR seems to be MIA for commented fixes and fork doesn't allow modifications from me. 

Implemented similar changes with slight modifications in PR's https://github.com/ronivay/xen-orchestra-docker/pull/28 & https://github.com/ronivay/xen-orchestra-docker/pull/30 

Closing this.

**Comment by ahinrichs** [comment]
> Maintainer of this PR seems to be unresponsive to add fixes based on comments and fork doesn't allow modifications from me.
> 
> Implemented similar changes with slight modifications in PR's #28 & #30
> 
> Closing this.

I checked the PR comments daily. What comments / proposed fixes did I miss that would have needed an action from me?

**Comment by ronivay** [comment]
> > Maintainer of this PR seems to be unresponsive to add fixes based on comments and fork doesn't allow modifications from me.
> > Implemented similar changes with slight modifications in PR's #28 & #30
> > Closing this.
> 
> I checked the PR comments daily. What comments / proposed fixes did I miss that would have needed an action from me?

Screen Shot 2023-11-02 at 14 30 28

**Comment by ahinrichs** [comment]
> > > Maintainer of this PR seems to be unresponsive to add fixes based on comments and fork doesn't allow modifications from me.
> > > Implemented similar changes with slight modifications in PR's #28 & #30
> > > Closing this.
> > 
> > 
> > I checked the PR comments daily. What comments / proposed fixes did I miss that would have needed an action from me?
> 
> Might've been my bad, started a review but guess it was left pending :)

Ok, never mind. I'm fine with the result :-)

**Comment by ronivay** [comment]
> > > > Maintainer of this PR seems to be unresponsive to add fixes based on comments and fork doesn't allow modifications from me.
> 
> > > > Implemented similar changes with slight modifications in PR's #28 & #30
> 
> > > > Closing this.
> 
> > > 
> 
> > > 
> 
> > > I checked the PR comments daily. What comments / proposed fixes did I miss that would have needed an action from me?
> 
> > 
> 
> > Might've been my bad, started a review but guess it was left pending :)
> 
> 
> 
> Ok, never mind. I'm fine with the result :-) I just wanted to be sure I didn't miss something relevant.

Yeah you didn't, i failed to press a button. Thanks for PR still :)

**Pull request closed without merging**
